import arrays.DVD;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
	
	// The actual code for creating an Array to hold DVD's.
	private static DVD[] dvdCollection = new DVD[15];
		
    public boolean someLibraryMethod() {
        return true;
    }
}
